version: '2'
services:
  webhook-handler:
    restart: always
    build: .
    container_name: reporting-webhook
    ports:
      - 5018:5018
    volumes:
      - ./logs:/var/log
  elasticsearch:
    restart: always
    image: elasticsearch:5.6-alpine
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
  kibana:
    restart: always
    image: kibana:5.6
    ports:
      - 5601:5601
    environment:
     ELASTICSEARCH_URL: http://elasticsearch:9200
